ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "goals" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "completedLessons" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN IF NOT EXISTS "highestUnlockedLesson" INTEGER NOT NULL DEFAULT 1;
