ALTER TABLE "User"
ADD COLUMN "goals" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "completedLessons" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN "highestUnlockedLesson" INTEGER NOT NULL DEFAULT 1;
